version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: nest-db-prueba
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 3331:5432
